# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cea241bdabb4235fc230f2acad4c3bfe6f2ac35c90ca4b24e99a2c6c57687209daea8fb817d663d5fcaf3eec5b756f4ac6b54ab97c6076022869fa58e18dd6bb

test:
  secret_key_base: 7793dd50a0ce9e5dd23edbd98ee3db8f3c38dbf2c56e3142bb1d24e44a381d212f5becfc5435a674bb3589af042b423d0daf0c907b53921e3d782b99ef133c56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
